# Generated by Django 5.2.11 on 2026-02-18 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SemenAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('volume_ml', models.DecimalField(decimal_places=2, max_digits=4)),
                ('concentration_million_per_ml', models.DecimalField(decimal_places=2, max_digits=5)),
                ('motility_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('morphology_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comments', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyst', models.ForeignKey(limit_choices_to={'role': 'andrology_tech'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='SpermFreezing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('straws_frozen', models.PositiveIntegerField()),
                ('barcode', models.CharField(max_length=64, unique=True)),
                ('thawed', models.BooleanField(default=False)),
                ('thawed_on', models.DateField(blank=True, null=True)),
                ('qc_check', models.CharField(blank=True, max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('processed_by', models.ForeignKey(limit_choices_to={'role': 'andrology_tech'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('witness', models.ForeignKey(blank=True, limit_choices_to={'role': 'andrology_tech'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='andrology_witness', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpermPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparation_type', models.CharField(choices=[('swim-up', 'Swim Up'), ('density', 'Density Gradient')], max_length=64)),
                ('date', models.DateField()),
                ('comments', models.CharField(blank=True, max_length=255)),
                ('processed_by', models.ForeignKey(limit_choices_to={'role': 'andrology_tech'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('semen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparations', to='andrology_lab.semenanalysis')),
            ],
        ),
    ]
