# Generated by Django 5.2.11 on 2026-02-18 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IVFCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('protocol', models.CharField(choices=[('long', 'Long Protocol'), ('antagonist', 'Antagonist'), ('minimal', 'Minimal Stimulation'), ('natural', 'Natural Cycle')], max_length=32)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('stimulation', 'Ovarian Stimulation'), ('retrieval', 'Egg Retrieval'), ('fertilization', 'Fertilization'), ('transfer', 'Embryo Transfer'), ('luteal_support', 'Luteal Support'), ('pregnancy_test', 'Pregnancy Test'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='registered', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('outcome', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ivf_cycles', to='patients.coupleprofile')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmbryoTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('embryos_transferred', models.PositiveSmallIntegerField()),
                ('quality', models.CharField(max_length=128)),
                ('outcome', models.CharField(blank=True, max_length=128)),
                ('ivf_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embryo_transfers', to='ivf.ivfcycle')),
            ],
        ),
        migrations.CreateModel(
            name='EggRetrieval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('eggs_collected', models.PositiveSmallIntegerField()),
                ('matured_eggs', models.PositiveSmallIntegerField()),
                ('comments', models.TextField(blank=True)),
                ('ivf_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egg_retrievals', to='ivf.ivfcycle')),
            ],
        ),
        migrations.CreateModel(
            name='StimulationDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('estradiol', models.FloatField(blank=True, null=True)),
                ('lh', models.FloatField(blank=True, null=True)),
                ('progesterone', models.FloatField(blank=True, null=True)),
                ('dominant_follicles', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('medication', models.CharField(blank=True, max_length=128)),
                ('note', models.CharField(blank=True, max_length=256)),
                ('ivf_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stimulation_days', to='ivf.ivfcycle')),
            ],
        ),
    ]
