# Generated by Django 5.2.11 on 2026-02-18 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('batch_number', models.CharField(max_length=64)),
                ('expiry_date', models.DateField()),
                ('quantity_in_stock', models.PositiveIntegerField()),
                ('controlled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionDispensing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('prescribed_by', models.CharField(max_length=128)),
                ('prescribed_to', models.CharField(max_length=128)),
                ('dispensed_on', models.DateField(auto_now_add=True)),
                ('issued_by', models.CharField(max_length=128)),
                ('note', models.TextField(blank=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drug')),
            ],
        ),
    ]
