# Generated by Django 5.2.11 on 2026-02-18 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ivf', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Embryo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField()),
                ('grade', models.CharField(max_length=16)),
                ('biopsy_done', models.BooleanField(default=False)),
                ('cryo_stored', models.BooleanField(default=False)),
                ('barcode', models.CharField(max_length=64, unique=True)),
                ('chain_of_custody', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ivf_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embryos', to='ivf.ivfcycle')),
                ('witness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embryo_witness', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Oocyte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retrieval_date', models.DateField()),
                ('number_retrieved', models.PositiveSmallIntegerField()),
                ('mature', models.PositiveSmallIntegerField()),
                ('comments', models.CharField(blank=True, max_length=255)),
                ('barcode', models.CharField(max_length=64, unique=True)),
                ('ivf_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oocytes', to='ivf.ivfcycle')),
                ('witness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oocyte_witness', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fertilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('method', models.CharField(choices=[('IVF', 'IVF'), ('ICSI', 'ICSI')], max_length=64)),
                ('fertilized', models.PositiveSmallIntegerField()),
                ('normal', models.PositiveSmallIntegerField()),
                ('abnormal', models.PositiveSmallIntegerField()),
                ('comments', models.TextField(blank=True)),
                ('oocyte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizations', to='embryology_lab.oocyte')),
            ],
        ),
    ]
