# Generated by Django 5.2.11 on 2026-02-18 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryotank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('capacity', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=64)),
                ('temperature', models.FloatField(default=-196.0)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('donor_type', models.CharField(choices=[('sperm', 'Sperm'), ('egg', 'Egg'), ('embryo', 'Embryo')], max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CryoStorageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specimen_type', models.CharField(choices=[('embryo', 'Embryo'), ('sperm', 'Sperm'), ('oocyte', 'Oocyte')], max_length=16)),
                ('canister', models.CharField(max_length=32)),
                ('goblet', models.CharField(max_length=32)),
                ('straw', models.CharField(max_length=32)),
                ('barcode', models.CharField(max_length=64, unique=True)),
                ('stored_on', models.DateField(auto_now_add=True)),
                ('withdrawn_on', models.DateField(blank=True, null=True)),
                ('consent_form', models.FileField(blank=True, null=True, upload_to='cryobank/consent/')),
                ('storage_billing_due', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('witness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryobank.cryotank')),
            ],
        ),
    ]
