# Generated by Django 5.2.11 on 2026-02-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_color', models.CharField(default='#667eea', max_length=7)),
                ('show_charts', models.BooleanField(default=True)),
                ('items_per_page', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name_plural': 'Dashboard Settings',
            },
        ),
    ]
