# Generated by Django 5.2.11 on 2026-02-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_remove_user_role_user_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('reception', '🎫 Front Office / Reception'), ('opd', '🏥 Outpatient Department (OPD)'), ('fertility_consultation', '🔍 Fertility Consultation Unit'), ('ivf', '🧬 IVF & ART Department'), ('andrology_lab', '🔬 Andrology Laboratory'), ('embryology_lab', '🥚 Embryology Laboratory'), ('ultrasound', '📡 Ultrasound & Imaging Department'), ('nursing', '   \u200d⚕️ Nursing Department'), ('pharmacy', '💊 Pharmacy Department'), ('billing', '💰 Finance & Billing Department'), ('general_lab', '🧪 General Laboratory (Diagnostics)'), ('counseling', '💭 Counseling & Psychology Unit'), ('cryobank', '❄️ Cryobank Management'), ('hr', '👔 Human Resource (HR)'), ('admin', '⚙️ Administration & Management')], default='reception', max_length=50),
        ),
    ]
